#!/usr/bin/env bash
set -euo pipefail

#function cleanup {
#  docker kill radicle-git-server-test
#}
#trap cleanup EXIT

PASSPHRASE=asdf
SEED="0.0.0.0:8080"

REPO_ROOT=$(git rev-parse --show-toplevel)
ID=$(echo $RANDOM | md5sum | head -c 8)
BASE_PATH=$REPO_ROOT/tests/tmp/create-seed-fixture-$ID

TEST_REPO_ARCHIVE=$REPO_ROOT/tests/fixtures/repos/source-browsing.tar.bz2
TEST_REPO_NAME=source-browsing
TEST_REPO_PATH=$BASE_PATH/repos/$TEST_REPO_NAME

PALM_RAD_HOME=$BASE_PATH/seeds/palm
ALICE_RAD_HOME=$BASE_PATH/peers/alice
ALICE_CHECKOUT=$BASE_PATH/checkout/alice
BOB_RAD_HOME=$BASE_PATH/peers/bob
BOB_CHECKOUT=$BASE_PATH/checkout/bob

mkdir -p $PALM_RAD_HOME
mkdir -p $ALICE_RAD_HOME
mkdir -p $ALICE_CHECKOUT
mkdir -p $BOB_RAD_HOME
mkdir -p $BOB_CHECKOUT
mkdir -p $TEST_REPO_PATH

tar -xf $TEST_REPO_ARCHIVE -C $TEST_REPO_PATH

RAD_HOME=$PALM_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad auth

#RAD_HOME=$PALM_RAD_HOME radicle-httpd &

# git-server takes a while to copy commit hooks to the monorepo
sleep 1

GIT_AUTHOR_NAME="Alice Liddell"
GIT_AUTHOR_EMAIL="alice@radicle.xyz"
GIT_COMMITTER_NAME="Alice Liddell"
GIT_COMMITTER_EMAIL="alice@radicle.xyz"

RAD_DEBUG=1 RAD_HOME=$ALICE_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad auth

cd $ALICE_CHECKOUT

git clone $TEST_REPO_PATH
cd $TEST_REPO_NAME
git checkout feature/branch
git checkout orphaned-branch
git checkout main

RAD_HOME=$ALICE_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad init --name "source-browsing" --description "Git repository for source browsing tests" --default-branch "main" --no-confirm
#RAD_HOME=$ALICE_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad push --seed $SEED --all --sync
PROJECT_ID=$(RAD_HOME=$ALICE_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad .)


#GIT_AUTHOR_NAME="Bob Belcher"
#GIT_AUTHOR_EMAIL="bob@radicle.xyz"
#GIT_COMMITTER_NAME="Bob Belcher"
#GIT_COMMITTER_EMAIL="bob@radicle.xyz"

#RAD_HOME=$BOB_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad auth

#cd $BOB_CHECKOUT
#RAD_HOME=$BOB_RAD_HOME rad clone $PROJECT_ID --seed $SEED --no-confirm

#cd $TEST_REPO_NAME
#echo "Updated readme" > README.md
#git add README.md
#git commit --message "Update readme" --date "Mon Nov 21 14:00 2022 +0100"
#RAD_HOME=$BOB_RAD_HOME rad push --seed $SEED
#RAD_HOME=$BOB_RAD_HOME rad sync --seed $SEED --self
#RAD_HOME=$BOB_RAD_HOME rad sync --seed $SEED

cd $BASE_PATH
#tar -cjf palm.tar.bz2 --exclude "post-receive" --exclude "pre-receive" -C $PALM_RAD_HOME .
tar -cjf palm.tar.bz2 --exclude "post-receive" --exclude "pre-receive" -C $ALICE_RAD_HOME .
