#!/usr/bin/env bash
set -euo pipefail

function cleanup {
  docker kill radicle-git-server-test
}
trap cleanup EXIT


PASSPHRASE=asdf
TAG=40bdc662b2d48cbfaa87182b21457ef8f861b04a

REPO_ROOT=$(git rev-parse --show-toplevel)
ID=$(echo $RANDOM | md5sum | head -c 8)
BASE_PATH=$REPO_ROOT/tests/tmp/create-seed-fixture-$ID

TEST_REPO_ARCHIVE=$REPO_ROOT/tests/fixtures/repos/source-browsing.tar.bz2
TEST_REPO_NAME=source-browsing
TEST_REPO_PATH=$BASE_PATH/repos/$TEST_REPO_NAME

PALM_LNK_HOME=$BASE_PATH/seeds/palm
ALICE_LNK_HOME=$BASE_PATH/peers/alice
ALICE_CHECKOUT=$BASE_PATH/checkout/alice
BOB_LNK_HOME=$BASE_PATH/peers/bob
BOB_CHECKOUT=$BASE_PATH/checkout/bob

mkdir -p $PALM_LNK_HOME
mkdir -p $ALICE_LNK_HOME
mkdir -p $ALICE_CHECKOUT
mkdir -p $BOB_LNK_HOME
mkdir -p $BOB_CHECKOUT
mkdir -p $TEST_REPO_PATH

tar -xf $TEST_REPO_ARCHIVE -C $TEST_REPO_PATH

LNK_HOME=$PALM_LNK_HOME rad auth --init --name palm --passphrase $PASSPHRASE

docker run \
  --detach \
  --init \
  --publish 8778:8778 \
  --rm \
  --env RAD_HOME=/app/radicle \
  --name radicle-git-server-test \
  --volume $PALM_LNK_HOME:/app/radicle \
  "gcr.io/radicle-services/git-server:$TAG" \
  --passphrase $PASSPHRASE \
  --allow-unauthorized-keys

# git-server takes a while to copy commit hooks to the monorepo
sleep 10

GIT_AUTHOR_NAME="Alice Liddell"
GIT_AUTHOR_EMAIL="alice@radicle.xyz"
GIT_COMMITTER_NAME="Alice Liddell"
GIT_COMMITTER_EMAIL="alice@radicle.xyz"

LNK_HOME=$ALICE_LNK_HOME rad auth --init --name alice --passphrase $PASSPHRASE

cd $ALICE_CHECKOUT

git clone $TEST_REPO_PATH
cd $TEST_REPO_NAME
git checkout feature/branch
git checkout orphaned-branch
git checkout main

LNK_HOME=$ALICE_LNK_HOME rad init --name "source-browsing" --description "Git repository for source browsing tests" --default-branch "main" --no-confirm
LNK_HOME=$ALICE_LNK_HOME rad push --seed 0.0.0.0:8778 --all --sync
PROJECT_URN=$(rad .)


GIT_AUTHOR_NAME="Bob Belcher"
GIT_AUTHOR_EMAIL="bob@radicle.xyz"
GIT_COMMITTER_NAME="Bob Belcher"
GIT_COMMITTER_EMAIL="bob@radicle.xyz"

LNK_HOME=$BOB_LNK_HOME rad auth --init --name bob --passphrase $PASSPHRASE

cd $BOB_CHECKOUT
LNK_HOME=$BOB_LNK_HOME rad clone $PROJECT_URN --seed 0.0.0.0:8778 --no-confirm

cd $TEST_REPO_NAME
echo "Updated readme" > README.md
git add README.md
git commit --message "Update readme" --date "Mon Nov 21 14:00 2022 +0100"
LNK_HOME=$BOB_LNK_HOME rad push --seed 0.0.0.0:8778
LNK_HOME=$BOB_LNK_HOME rad sync --seed 0.0.0.0:8778 --self
LNK_HOME=$BOB_LNK_HOME rad sync --seed 0.0.0.0:8778

cd $BASE_PATH
tar -cjf palm.tar.bz2 --exclude "post-receive" --exclude "pre-receive" -C $PALM_LNK_HOME .
